export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const POST_PRODUCTS_SUCCESS = "POST_PRODUCTS_SUCCESS";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";
export const DELETE_PRODUCT_SUCCESS ="DELETE_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_SUCCESS="EDIT_PRODUCT_SUCCESS"